<a href="https://colab.research.google.com/github/paolayela/Talento-TECH/blob/main/explicacion_numerica_de_MLP_Funciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# explicacion_numerica_de_MLP

Por:

Andrés Felipe Escallón Portilla
(21-junio-2024)

*Referencias:

- https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-activity-7171891528448008192-nulK/?utm_source=share&utm_medium=member_android

- https://www.linkedin.com/posts/tom-yeh_deeplearning-llms-generativeai-activity-7161408843111956480-ujq0/

- https://alfanotv.com/raspberry-pi/como-multiplicar-matrices-en-numpy-multiply-matmul/

- https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-ugcPost-7174203548736319488-RM0S?utm_source=share&utm_medium=member_android

In [2]:
import numpy as np

array_1 = np.array(     [ [1, 1], [-1,1] ]   )


W = np.array(     [ [1, 1], [-1,1] ]   )
print("\n W = \n", W)
#print()


array_2 = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )

X = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )
print("\n X = \n",X)
#print()

WX_1 = np.dot(W,X)
print("\n WX_1 = \n",WX_1)
#print()

WX_2 = np.matmul(W,X)
print("\n WX_2 = \n",WX_2)
#print()

#XW = np.matmul(X,W)
#print(XW)
#print()
# Lo anterior no funciona por lo siguiente:
#X_(2,3) por W_(2,2) = Resultado_(2,2)?
#porque el numero de columnas de X es diferente al numero de filas de W


 W = 
 [[ 1  1]
 [-1  1]]

 X = 
 [[1 5 2]
 [2 4 2]]

 WX_1 = 
 [[ 3  9  4]
 [ 1 -1  0]]

 WX_2 = 
 [[ 3  9  4]
 [ 1 -1  0]]



```
W_(2,2) por X_(2,3) = WX_(2,3)

W*x + b = Z ---> Activation = output

W_(3,4) por x_(4,5) = Z_(3,5)

Asumiendo que todos los biases son cero y que NO hay función de activación (es decir: se deja pasar la misma información)

```


In [3]:
W = np.array([   [1,1,0,-1], [-1,1,2,-3], [-1,1,5,0]  ])
print(W)

print()

x = np.array([ [1,5,2,-1,0], [2,4,2,1,-1], [7,5,6,-1,1], [-8,0,4,-1,3] ])
print(x)
print()

b = np.zeros((3, 5)) # suponer todos los valores de los biases en cero
print(b)
print()

Z = np.matmul(W,x) + b
print(Z)

[[ 1  1  0 -1]
 [-1  1  2 -3]
 [-1  1  5  0]]

[[ 1  5  2 -1  0]
 [ 2  4  2  1 -1]
 [ 7  5  6 -1  1]
 [-8  0  4 -1  3]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[11.  9.  0.  1. -4.]
 [39.  9.  0.  3. -8.]
 [36. 24. 30. -3.  4.]]


# Explicación manual:

```
W =
[[ 1  1]
 [-1  1]]

x=
 [[1 5 2]
 [2 4 2]]

Entonces:

W*x + b:

b=zeros
W*x  + 0 = W*x = Z
[[ 3  9  4]
 [ 1 -1  0]]

Z-->relu-->A
A=
[[ 3  9  4]
 [ 1  0  0]]

===============
W*x =
[[ 3  9  4]
 [ 1 -1  0]]

+ b (b=ones)
W*x + b:
[[ 4  10  5]
 [ 2  0   1]]

W*x + b = Z
Z-->relu-->A

A=
[[ 4  10  5]
 [ 2  0   0]]

=========================

Comparar el resultado conocido (Supervisado)
Supongamos que el resultado conocido es:
Y_real=
[[ 4  10  5]
 [ 2  0   0]]
y sucedió que la red calculó y dio:
A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ 0  0  0]
 [ 0  0   0]]

===============================================
O supongamos que el resultado conocido debe ser:
Y_real=
[[ -3  6  2]
 [ 0   5 -1]]
y sucedió que la red calculó y dio:

A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ -7  -4  -3]
 [ -2  5   -1]]


```






# Operaciones correctas vs incorrectas:

## Si no se cumple lo dicho incialmente, entonces no se puede multiplicar matrices desde el procedimiento de algebra lineal:

## "*" y multiply son para multiplicar elemento a elemento matrices del mismo tamaño = num_filas x num_columnas

In [4]:
#array_r_bad1 = array_1 * array_2
#print(array_r_bad1)

np.array([1,1])*np.array([1,1,1])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [5]:
print(np.array([2,4])*np.array([3,-5]))

[  6 -20]


In [6]:
np.multiply(np.array([2,4]), np.array([3,-5]))

array([  6, -20])

In [7]:
array_r_bad2 = array_2 * array_1
print(array_r_bad2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [8]:
mult3 = np.multiply(array_1,array_2)
print(mult3)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

# HOMEWORK:

# Ejemplo académico:

Definiendo funciones en python para calcular:

 W x + b = Z --> relu ---> y

In [23]:
def get_output_from_MLP_input(W,x,b,activation="linear"):
  #print("W = ",end='\n')
  #print(W)
  print(f"W = \n {W} \n")
  #print()

  print("x = ",end='\n')
  print(x)
  print("b = ",end='\n')
  print(b)
  # arguments:
  # W,x and b are arrays

  # operations
  # Z = W x  +  b
  #Z = np.matmul(W,x) + b
  Z = np.dot(W,x) + b

  print("Z = ",end='\n')
  print(Z)

  if activation=="linear":
    y = Z

  if activation=="relu":
    # Ternary operator to define a relu function
    #y = Z if Z>=0 else 0
    #y = Z if Z>0 else 0
    #y = 0 if Z<0 else Z
    #y = 0 if Z<=0 else Z
    y = np.array([0 if z<=0 else z for z in Z])

  #TO-DO:

  if activation=="sigmoid":
    y=([1/(1+(2.71)**-Z)])


  if activation=="tanh":
    y=((((2.71)**Z)-((2.71)**-Z))/(((2.71)**Z)+((2.71)**-Z)))

  if activation=="leakyrelu":
    alpha=0.01
    y = np.array([z if z>=0 else z*alpha for z in Z])



  print("y = ",end='\n')
  print(y)

  return y

In [10]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b)
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1  3  5  3]


array([-1,  3,  5,  3])

In [19]:
# Testing (relu)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"relu")
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0 3 5 3]


array([0, 3, 5, 3])

In [17]:
# Testing (sigmoide)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"sigmoid")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[array([0.26954178, 0.95215886, 0.99320495, 0.95215886])]


In [22]:
# Testing (Than)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"tanh")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.76030968  0.99496361  0.99990639  0.99496361]


In [24]:
# Testing (Than)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"leakyrelu")

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.01  3.    5.    3.  ]


# Ojo: la multiplicacion entre matrices en general NO es conmutativa

AB=C en general es distinto de BA=D

(suponiendo que por las dimensiones se puedan operar)

Ejemplo: al intercambiar Wx con xW hay error

In [ ]:
y = get_output_from_MLP_input(x,W,b)

W = 
 [2 1 3] 

x = 
[[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]]
b = 
[-5  0  1 -2]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)